import Head from "next/head";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="container">
        <h1>Hello world</h1>
        <p>How are you doing today?</p>
        <a href="#">Test link</a>
      </div>
    </>
  );
}
